export const gods = [
    // Carry
    { id: 33, name: 'Aladdin', image: 'https://via.placeholder.com/100', roles: ['Jungle'] },
    { id: 11, name: 'Agni', image: 'https://via.placeholder.com/100', roles: ['Mid'] },
    { id: 27, name: 'Achilles', image: 'https://via.placeholder.com/100', roles: ['Solo'] },
    { id: 28, name: 'Amaterasu', image: 'https://via.placeholder.com/100', roles: ['Solo'] },
    { id: 42, name: 'Anhur', image: 'https://via.placeholder.com/100', roles: ['Carry'] },
    { id: 13, name: 'Anubis', image: 'https://via.placeholder.com/100', roles: ['Mid'] },
    { id: 43, name: 'Apollo', image: 'https://via.placeholder.com/100', roles: ['Carry'] },
    {   
        id: 1,
        name: 'Ares',
        image: 'https://webcdn.hirezstudios.com/smite/god-icons/ares.jpg',
        roles: ['Support'],
        skins: ["https://wiki.smite2.com/images/thumb/T_Ares_TokyoKnight_Card.png/720px-T_Ares_TokyoKnight_Card.png?6d580"],
        voiceLine: "" 
    },
    { id: 44, name: 'Artemis', image: 'https://via.placeholder.com/100', roles: ['Carry'] },
    { id: 2, name: 'Athena', image: 'https://via.placeholder.com/100', roles: ['Support'] },
    { id: 34, name: 'Awilix', image: 'https://via.placeholder.com/100', roles: ['Jungle'] },
    { id: 3, name: 'Bacchus', image: 'https://via.placeholder.com/100', roles: ['Support'] },
    { id: 29, name: 'Bellona', image: 'https://via.placeholder.com/100', roles: ['Solo'] },
    { id: 4, name: 'Cabrakan', image: 'https://via.placeholder.com/100', roles: ['Solo'] },
    { id: 5, name: 'Cerberus', image: 'https://via.placeholder.com/100', roles: ['Solo'] },
    { id: 45, name: 'Cernunnos', image: 'https://via.placeholder.com/100', roles: ['Carry'] },
    { id: 30, name: 'Chaac', image: 'https://via.placeholder.com/100', roles: ['Solo'] },
    { id: 46, name: 'Cupid', image: 'https://via.placeholder.com/100', roles: ['Carry'] },
    { id: 47, name: 'Danzaburou', image: 'https://via.placeholder.com/100', roles: ['Carry'] },
    { id: 35, name: 'Fenrir', image: 'https://via.placeholder.com/100', roles: ['Jungle'] },
    { id: 7, name: 'Geb', image: 'https://via.placeholder.com/100', roles: ['Support', 'Solo'] },
    { id: 31, name: 'Guan Yu', image: 'https://via.placeholder.com/100', roles: ['Solo'] },
    { id: 57, name: 'Hercules', image: 'https://via.placeholder.com/100', roles: ['Solo'] },
    { id: 60, name: 'Hun Batz', image: 'https://via.placeholder.com/100', roles: ['Jungle'] },
    { id: 48, name: 'Izanami', image: 'https://via.placeholder.com/100', roles: ['Carry'] },
    { id: 49, name: 'Jing Wei', image: 'https://via.placeholder.com/100', roles: ['Carry'] },
    { id: 36, name: 'Kali', image: 'https://via.placeholder.com/100', roles: ['Jungle'] },
    { id: 8, name: 'Khepri', image: 'https://via.placeholder.com/100', roles: ['Support'] },
    { id: 18, name: 'Kukulkan', image: 'https://via.placeholder.com/100', roles: ['Mid'] },
    { id: 37, name: 'Loki', image: 'https://via.placeholder.com/100', roles: ['Jungle'] },
    { id: 50, name: 'Medusa', image: 'https://via.placeholder.com/100', roles: ['Carry'] },
    { id: 38, name: 'Mercury', image: 'https://via.placeholder.com/100', roles: ['Jungle'] },
    { id: 19, name: 'Merlin', image: 'https://via.placeholder.com/100', roles: ['Mid'] },
    { id: 32, name: 'Mulan', image: 'https://via.placeholder.com/100', roles: ['Solo'] },
    { id: 51, name: 'Neith', image: 'https://via.placeholder.com/100', roles: ['Carry'] },
    { id: 39, name: 'Nemesis', image: 'https://via.placeholder.com/100', roles: ['Jungle'] },
    { id: 20, name: 'Nu Wa', image: 'https://via.placeholder.com/100', roles: ['Mid'] },
    { id: 58, name: 'Odin', image: 'https://via.placeholder.com/100', roles: ['Solo'] },
    { id: 61, name: 'Pele', image: 'https://via.placeholder.com/100', roles: ['Jungle'] },
    { id: 21, name: 'Poseidon', image: 'https://via.placeholder.com/100', roles: ['Mid'] },
    { id: 55, name: 'Ra', image: 'https://via.placeholder.com/100', roles: ['Mid'] },
    { id: 52, name: 'Rama', image: 'https://via.placeholder.com/100', roles: ['Carry'] },
    { id: 23, name: 'Scylla', image: 'https://via.placeholder.com/100', roles: ['Mid'] },
    { id: 9, name: 'Sobek', image: 'https://via.placeholder.com/100', roles: ['Support'] },
    { id: 24, name: 'Sol', image: 'https://via.placeholder.com/100', roles: ['Carry'] },
    { id: 59, name: 'Sun Wukong', image: 'https://via.placeholder.com/100', roles: ['Solo'] },
    { id: 40, name: 'Susano', image: 'https://via.placeholder.com/100', roles: ['Jungle'] },
    { id: 41, name: 'Thanatos', image: 'https://via.placeholder.com/100', roles: ['Jungle'] },
    { id: 62, name: 'Thor', image: 'https://via.placeholder.com/100', roles: ['Jungle'] },
    { id: 53, name: 'Ullr', image: 'https://via.placeholder.com/100', roles: ['Carry'] },
    { id: 56, name: 'Vulcan', image: 'https://via.placeholder.com/100', roles: ['Mid'] },
    { id: 54, name: 'Yemoja', image: 'https://via.placeholder.com/100', roles: ['Support'] },
    { id: 10, name: 'Ymir', image: 'https://via.placeholder.com/100', roles: ['Support'] },
    { id: 26, name: 'Zeus', image: 'https://via.placeholder.com/100', roles: ['Mid'] }
]